version: "3.7"

services:
  mysql:
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: ecs
      MYSQL_DATABASE: ecs
    volumes:
      - ./scripts:/ecs/scripts
      - ./script.sh:/ecs/script.sh
      - ./init-db.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: [ "CMD", "bash", "-c", "mysql -u root -pecs -e 'SELECT 1'" ]
      interval: 5s
      timeout: 10s
      start_period: 10s